# 默认请求头
default_header:
  User-Agent : Mozilla/5.0 (Windows NT 5.2) AppleWebKit/537.22 (KHTML, like Gecko) Chrome/25.0.1364.84 Safari/537.22
  Referer: http://e.jd.com/ebook.html
  connection: keep-alive
  cache-control: max-age=0
  accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
  accept-language: zh-CN,zh;q=0.8

cookie: __utma=122270672.572055792.1368524510.1368524510.1368524510.1;

# 数据库连接参数
host: localhost
port: 3306
user: root
passwd: "314"
charset: utf8
# 详细数据库信息
db_name: ebook
book_table_name: shotbook
chapter_table_name: chapter
# 主机
dohost: A1

# 客户端参数
all_sql: select * from shotbook limit 1
col_num: 5 # 默认选图列数
page_count: 20 # 每页图片数
img_width: 200 # 默认图像宽度
img_height: 333 # 默认图像高度

# 文件下载根路径
rootpath: F:/ebook/

# 书籍最大允许大小，单位Kb
max_book_size: 3000

# 所有坐标信息
fhsj_pos_sleep: [109, 74, 1] # 返回书架位置
wdcd_pos_sleep: [112, 205, 1] # 我的畅读位置
sx_pos_sleep: [345, 71, 3] # 刷新
zxcd_first_pos_sleep: [492, 171, 1] # 在线畅读第一本数的位置
down_pos_sleep: [910, 912, 0.5] # 书籍出下三角位置
start_pos: [145, 153] # 截图左上角坐标
shot_size: [480, 800] # 截图大小
inner_blank_sleep: [354, 467, 0.2] # 书内空白位置
next_pos_sleep: [666, 568, 0.2] # 下一页位置，延时
blod_para: [3, 3, 65] # 识别粗体的参数
equal_times: 5 # 判断几次图片一样则这本书抓取结束
