# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\eclipse4.2\BookClient\BookMain.ui'
#
# Created: Wed Jul 31 18:23:48 2013
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(934, 799)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.splitter = QtGui.QSplitter(self.centralWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.booksLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.booksLayout.setMargin(0)
        self.booksLayout.setObjectName(_fromUtf8("booksLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pBtn1 = QtGui.QPushButton(self.layoutWidget)
        self.pBtn1.setObjectName(_fromUtf8("pBtn1"))
        self.horizontalLayout.addWidget(self.pBtn1)
        self.booksLayout.addLayout(self.horizontalLayout)
        self.bookListWidget = QtGui.QListWidget(self.layoutWidget)
        self.bookListWidget.setBaseSize(QtCore.QSize(60, 0))
        self.bookListWidget.setObjectName(_fromUtf8("bookListWidget"))
        self.booksLayout.addWidget(self.bookListWidget)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.saveBookInfoBtn = QtGui.QPushButton(self.layoutWidget1)
        self.saveBookInfoBtn.setObjectName(_fromUtf8("saveBookInfoBtn"))
        self.verticalLayout.addWidget(self.saveBookInfoBtn)
        self.coverImgLabel = QtGui.QLabel(self.layoutWidget1)
        self.coverImgLabel.setObjectName(_fromUtf8("coverImgLabel"))
        self.verticalLayout.addWidget(self.coverImgLabel)
        self.upCoverBtn = QtGui.QPushButton(self.layoutWidget1)
        self.upCoverBtn.setObjectName(_fromUtf8("upCoverBtn"))
        self.verticalLayout.addWidget(self.upCoverBtn)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_6 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_8.addWidget(self.label_6)
        self.nidEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.nidEdit.setObjectName(_fromUtf8("nidEdit"))
        self.horizontalLayout_8.addWidget(self.nidEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.bookNameEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.bookNameEdit.setObjectName(_fromUtf8("bookNameEdit"))
        self.horizontalLayout_3.addWidget(self.bookNameEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.authorEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.authorEdit.setObjectName(_fromUtf8("authorEdit"))
        self.horizontalLayout_4.addWidget(self.authorEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_3 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        self.typeEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.typeEdit.setObjectName(_fromUtf8("typeEdit"))
        self.horizontalLayout_5.addWidget(self.typeEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_4 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        self.createTimeEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.createTimeEdit.setObjectName(_fromUtf8("createTimeEdit"))
        self.horizontalLayout_6.addWidget(self.createTimeEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_5 = QtGui.QLabel(self.layoutWidget1)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_7.addWidget(self.label_5)
        self.descriptionEdit = QtGui.QTextEdit(self.layoutWidget1)
        self.descriptionEdit.setObjectName(_fromUtf8("descriptionEdit"))
        self.horizontalLayout_7.addWidget(self.descriptionEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.layoutWidget2 = QtGui.QWidget(self.splitter)
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pBtn2 = QtGui.QPushButton(self.layoutWidget2)
        self.pBtn2.setObjectName(_fromUtf8("pBtn2"))
        self.horizontalLayout_2.addWidget(self.pBtn2)
        self.pBtn3 = QtGui.QPushButton(self.layoutWidget2)
        self.pBtn3.setObjectName(_fromUtf8("pBtn3"))
        self.horizontalLayout_2.addWidget(self.pBtn3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_7 = QtGui.QLabel(self.layoutWidget2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_9.addWidget(self.label_7)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.nowPageLabel = QtGui.QLabel(self.layoutWidget2)
        self.nowPageLabel.setObjectName(_fromUtf8("nowPageLabel"))
        self.verticalLayout_2.addWidget(self.nowPageLabel)
        self.allPageLabel = QtGui.QLabel(self.layoutWidget2)
        self.allPageLabel.setObjectName(_fromUtf8("allPageLabel"))
        self.verticalLayout_2.addWidget(self.allPageLabel)
        self.horizontalLayout_9.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.previousBtn = QtGui.QPushButton(self.layoutWidget2)
        self.previousBtn.setObjectName(_fromUtf8("previousBtn"))
        self.horizontalLayout_10.addWidget(self.previousBtn)
        self.nextBtn = QtGui.QPushButton(self.layoutWidget2)
        self.nextBtn.setObjectName(_fromUtf8("nextBtn"))
        self.horizontalLayout_10.addWidget(self.nextBtn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.chapListWidget = QtGui.QListWidget(self.layoutWidget2)
        self.chapListWidget.setBaseSize(QtCore.QSize(60, 0))
        self.chapListWidget.setObjectName(_fromUtf8("chapListWidget"))
        self.verticalLayout_3.addWidget(self.chapListWidget)
        self.imgTableWidget = QtGui.QTableWidget(self.splitter)
        self.imgTableWidget.setBaseSize(QtCore.QSize(500, 0))
        self.imgTableWidget.setObjectName(_fromUtf8("imgTableWidget"))
        self.imgTableWidget.setColumnCount(0)
        self.imgTableWidget.setRowCount(0)
        self.verticalLayout_4.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.pBtn1.setText(_translate("MainWindow", "Refresh", None))
        self.saveBookInfoBtn.setText(_translate("MainWindow", "Save Book Info", None))
        self.coverImgLabel.setText(_translate("MainWindow", "TextLabel", None))
        self.upCoverBtn.setText(_translate("MainWindow", "Update Cover", None))
        self.label_6.setText(_translate("MainWindow", "nid", None))
        self.label.setText(_translate("MainWindow", "bookName", None))
        self.label_2.setText(_translate("MainWindow", "author", None))
        self.label_3.setText(_translate("MainWindow", "type", None))
        self.label_4.setText(_translate("MainWindow", "createTime", None))
        self.label_5.setText(_translate("MainWindow", "desc", None))
        self.pBtn2.setText(_translate("MainWindow", "Save", None))
        self.pBtn3.setText(_translate("MainWindow", "Clear", None))
        self.label_7.setText(_translate("MainWindow", "Page Now/All", None))
        self.nowPageLabel.setText(_translate("MainWindow", "0", None))
        self.allPageLabel.setText(_translate("MainWindow", "0", None))
        self.previousBtn.setText(_translate("MainWindow", "Previous", None))
        self.nextBtn.setText(_translate("MainWindow", " Next", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

